services:
  wyoming-nemo-stt:
    build: .
    container_name: wyoming-nemo-stt
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PORT=10600
      - MODEL_NAME=stt_es_conformer_ctc_large
    ports:
      - "10600:10600"  # puerto Wyoming
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: bash wyoming_entrypoint.sh
