services:
  wyoming-nemo-stt:
    build: .
    container_name: wyoming-nemo-stt
#    runtime: nvidia
    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_NAME=stt_es_conformer_ctc_large
    ports:
      - "10300:10300"  # puerto Wyoming
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: bash wyoming_entrypoint.sh
